//get article
export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_LATEST_ARTICLE = 'GET_LATEST_ARTICLE'
export const GET_ARTICLE_PENDING = 'GET_ARTICLE_PENDING'
export const GET_CATEGORY_DETAIL = 'GET_CATEGORY_DETAIL'
export const GET_CATEGORY_DETAILL = 'GET_CATEGORY_DETAILL'
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'
export const REGISTER_USER = 'REGISTER_USER'